#!/bin/csh -f

# Wrapper around projrep.pl and faults.pl to generate 7-day operations
# summary for the opsmeeting.

set tel = "JCMT"
set meeting = "opsmeeting"

#set tel = "UKIRT"
#set meeting = "schedmeeting"

set OPSMEETING_DIR = `dirname $0`
set OPSMEETING_DIR = `readlink -f $OPSMEETING_DIR`

echo ""
echo "This utility creates the projects, accounting and faults sections"
echo "for the ${meeting} minutes."

if ($?1) then
  set utstart = "$1"
else
  echo ""
  echo -n "Start UT date (i.e. last week friday HST) yyyymmdd: "
  set utstart = $<
endif

if ($utstart < 20000101 || $utstart > 20200101) then
  echo ""
  echo "ERROR: '$utstart' is not a valid YYYYMMDD date"
  echo ""
  exit
endif

echo ""
echo "Running project summary for 7 nights starting ${utstart} UT"
echo "...(can take a minute)..."

${OPSMEETING_DIR}/projrep.pl -tel "$tel" $utstart >! ${meeting}.rep

echo "Running faults  summary for 7 nights starting ${utstart} UT"
echo "..."

${OPSMEETING_DIR}/faults.pl  -tel "$tel" $utstart >> ${meeting}.rep

echo ""
echo "Finished: result is in the file '${meeting}.rep'"
echo "You need to review the closed faults and only keep"
echo "significant older faults."

echo ""
