CREATE TABLE `AZEL` (
  `projid` varchar(16) DEFAULT NULL,
  `scan` double DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `raj2000` double DEFAULT NULL,
  `decj2000` double DEFAULT NULL,
  `strt_az` double DEFAULT NULL,
  `strt_el` double DEFAULT NULL,
  `end_az` double DEFAULT NULL,
  `end_el` double DEFAULT NULL,
  `utstart` varchar(19) NOT NULL,
  `utstop` varchar(19) NOT NULL,
  UNIQUE KEY `AZELutind` (`ut`),
  KEY `AZELendazind` (`end_az`),
  KEY `AZELendelind` (`end_el`),
  KEY `AZELprojind` (`projid`),
  KEY `AZELstrtazind` (`strt_az`),
  KEY `AZELstrtelind` (`strt_el`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `AZEL2` (
  `projid` varchar(16) DEFAULT NULL,
  `scan` double DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `raj2000` double DEFAULT NULL,
  `decj2000` double DEFAULT NULL,
  `strt_az` double DEFAULT NULL,
  `strt_el` double DEFAULT NULL,
  `end_az` double DEFAULT NULL,
  `end_el` double DEFAULT NULL,
  `utstart` varchar(19) NOT NULL,
  `utstop` varchar(19) NOT NULL,
  `strt_f2` float DEFAULT NULL,
  `end_f2` float DEFAULT NULL,
  `avg_f2` float NOT NULL,
  UNIQUE KEY `AZEL2utind` (`ut`),
  KEY `AZELavgf2ind` (`avg_f2`),
  KEY `AZELendazind` (`end_az`),
  KEY `AZELendelind` (`end_el`),
  KEY `AZELprojind` (`projid`),
  KEY `AZELstrtazind` (`strt_az`),
  KEY `AZELstrtelind` (`strt_el`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `CAL` (
  `cal#` decimal(9,0) NOT NULL,
  `date` datetime DEFAULT NULL,
  `mode` varchar(8) DEFAULT NULL,
  `lofreq` double DEFAULT NULL,
  `freq` double DEFAULT NULL,
  `rx` varchar(8) DEFAULT NULL,
  `sbmode` char(3) DEFAULT NULL,
  `flag` smallint(6) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  UNIQUE KEY `CALdateind` (`date`),
  KEY `CALlofreqind` (`lofreq`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `CRYO` (
  `cryo#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `userid` varchar(16) DEFAULT NULL,
  `notes` varchar(64) DEFAULT NULL,
  `p_vacuum` float DEFAULT NULL,
  `p_optbox` float DEFAULT NULL,
  `lhe_level` float DEFAULT NULL,
  `lhe_boiloff` float DEFAULT NULL,
  `dewar_ln2_trap` float DEFAULT NULL,
  `dewar_ln2_shield` float DEFAULT NULL,
  `cold_trap_ln2` float DEFAULT NULL,
  `p1` float DEFAULT NULL,
  `p2` float DEFAULT NULL,
  `g1` float DEFAULT NULL,
  `g2` float DEFAULT NULL,
  `d1` float DEFAULT NULL,
  `d2` float DEFAULT NULL,
  `d4` float DEFAULT NULL,
  `d5` float DEFAULT NULL,
  `d8` float DEFAULT NULL,
  `bridge_res` float DEFAULT NULL,
  `array_temp` float DEFAULT NULL,
  `battery_no` int(11) DEFAULT NULL,
  `fet_lw` float DEFAULT NULL,
  `fet_sw` float DEFAULT NULL,
  `tuple_id` int(11) DEFAULT NULL,
  UNIQUE KEY `CRYOcryoind` (`cryo#`),
  KEY `CRYOut` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `CSONIGHT` (
  `utdate` datetime DEFAULT NULL,
  `avgtau` double DEFAULT NULL,
  `month` decimal(18,6) DEFAULT NULL,
  `grade` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `CSOTAU` (
  `tau#` bigint(20) NOT NULL AUTO_INCREMENT,
  `cso_ut` datetime DEFAULT NULL,
  `hst` float DEFAULT NULL,
  `tau` float DEFAULT NULL,
  `tau_rms` float DEFAULT NULL,
  `cso_ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  PRIMARY KEY (`tau#`),
  UNIQUE KEY `CSOTAUcsoutind` (`cso_ut`),
  KEY `CSOTAUcsodmfind` (`cso_ut_dmf`),
  KEY `CSOTAUtupind` (`tuple_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `CSOTEMP` (
  `tau#` int(11) DEFAULT NULL,
  `cso_ut` datetime DEFAULT NULL,
  `hst` float DEFAULT NULL,
  `uthh` decimal(18,6) DEFAULT NULL,
  `tau` float DEFAULT NULL,
  `tau_rms` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `DBLOG` (
  `projid` varchar(16) DEFAULT NULL,
  `scan` double DEFAULT NULL,
  `utstart` datetime DEFAULT NULL,
  `utstop` datetime DEFAULT NULL,
  UNIQUE KEY `DBLOGut1ind` (`utstart`),
  KEY `DBLOGprojind` (`projid`),
  KEY `DBLOGut2ind` (`utstop`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `FLUX` (
  `flux#` int(11) DEFAULT NULL,
  `ut` double DEFAULT NULL,
  `run` smallint(6) DEFAULT NULL,
  `flux` double DEFAULT NULL,
  `sn` double DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `FLUXflux#ind` (`flux#`),
  KEY `FLUXobject` (`object`),
  KEY `FLUXutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `LINE` (
  `line#` int(11) DEFAULT NULL,
  `line` varchar(16) DEFAULT NULL,
  `restfrq` double DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `LINEtupind` (`tuple_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `LOG` (
  `log#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `proj_id` varchar(16) DEFAULT NULL,
  `run` int(11) DEFAULT NULL,
  `status` varchar(16) DEFAULT NULL,
  `comment` varchar(255) NOT NULL,
  `active` smallint(6) DEFAULT NULL,
  UNIQUE KEY `LOGlog#ind` (`log#`),
  KEY `LOGutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `MIXER` (
  `mix#` decimal(9,0) NOT NULL,
  `date` datetime DEFAULT NULL,
  `mixid` smallint(6) DEFAULT NULL,
  `trx_mean` double DEFAULT NULL,
  `trx_sd` double DEFAULT NULL,
  `tsys_mean` double DEFAULT NULL,
  `tsys_sd` double DEFAULT NULL,
  UNIQUE KEY `MIXdatemix` (`date`,`mixid`),
  KEY `MIXmixid` (`mix#`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `MOTOR` (
  `motor#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `userid` varchar(16) DEFAULT NULL,
  `sector` int(11) DEFAULT NULL,
  `mtrInSector` int(11) DEFAULT NULL,
  `wRefFound` tinyint(4) NOT NULL,
  `phaseErr` tinyint(4) NOT NULL,
  `slotErr` tinyint(4) NOT NULL,
  `wheelErr` tinyint(4) NOT NULL,
  `slotTB` tinyint(4) NOT NULL,
  `wheelTB` tinyint(4) NOT NULL,
  `phaseMSB` tinyint(4) NOT NULL,
  `phase2` tinyint(4) NOT NULL,
  `phase1` tinyint(4) NOT NULL,
  `phaseLSB` tinyint(4) NOT NULL,
  `softMask` tinyint(4) NOT NULL,
  `phaseMask` tinyint(4) NOT NULL,
  `slotMask` tinyint(4) NOT NULL,
  `wheelMask` tinyint(4) NOT NULL,
  `motorInvalid` tinyint(4) NOT NULL,
  `motorDisable` tinyint(4) NOT NULL,
  `phase` int(11) DEFAULT NULL,
  `crpos` int(11) DEFAULT NULL,
  `stepr` int(11) DEFAULT NULL,
  `datum` int(11) DEFAULT NULL,
  `hilim` int(11) DEFAULT NULL,
  `lolim` int(11) DEFAULT NULL,
  `hslot` int(11) DEFAULT NULL,
  `lslot` int(11) DEFAULT NULL,
  `wlref` int(11) DEFAULT NULL,
  `wlent` int(11) DEFAULT NULL,
  `activ` int(11) DEFAULT NULL,
  `diff` int(11) DEFAULT NULL,
  `notes` varchar(40) DEFAULT NULL,
  `tuple_id` int(11) DEFAULT NULL,
  UNIQUE KEY `MOTORmotorind` (`motor#`),
  KEY `MOTORutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `NOI` (
  `noi#` int(11) DEFAULT NULL,
  `channel` char(3) DEFAULT NULL,
  `chop` float DEFAULT NULL,
  `chop_err` float DEFAULT NULL,
  `cal` float DEFAULT NULL,
  `cal_err` float DEFAULT NULL,
  `quality` int(11) DEFAULT NULL,
  `ut` datetime NOT NULL,
  `chop_thr` float DEFAULT NULL,
  `source` varchar(16) DEFAULT NULL,
  `az` float DEFAULT NULL,
  `el` float DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `NOItupind` (`tuple_id`),
  UNIQUE KEY `NOInoi#ind` (`noi#`),
  KEY `NOIutdmfind` (`ut_dmf`),
  KEY `NOIutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `RXTAU` (
  `projid` varchar(16) DEFAULT NULL,
  `scan` double DEFAULT NULL,
  `frontend` varchar(16) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `tau` float DEFAULT NULL,
  `inttime` float DEFAULT NULL,
  UNIQUE KEY `RXTAUut` (`ut`),
  KEY `RXprojid` (`projid`),
  KEY `RXrx` (`frontend`),
  KEY `RXtau` (`tau`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `SAOPHA` (
  `pha#` int(11) DEFAULT NULL,
  `sao_ut` datetime DEFAULT NULL,
  `hst` float DEFAULT NULL,
  `pha` float DEFAULT NULL,
  `seeing` float DEFAULT NULL,
  `sao_ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `SAOPHApha#ind` (`pha#`),
  KEY `SAOPHAsaodmfind` (`sao_ut_dmf`),
  KEY `SAOPHAsaoutind` (`sao_ut`),
  KEY `SAOPHAtupind` (`tuple_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `SCA` (
  `sca#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `ses#` int(11) DEFAULT NULL,
  `sou#` int(11) DEFAULT NULL,
  `wea#` int(11) DEFAULT NULL,
  `tel#` int(11) DEFAULT NULL,
  `gsdfile` varchar(120) DEFAULT NULL,
  `projid` varchar(16) DEFAULT NULL,
  `scan` double DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `object2` varchar(16) DEFAULT NULL,
  `frontend` varchar(16) DEFAULT NULL,
  `frontype` varchar(16) DEFAULT NULL,
  `nofchan` int(11) DEFAULT NULL,
  `backend` varchar(16) DEFAULT NULL,
  `backtype` varchar(16) DEFAULT NULL,
  `nobchan` int(11) DEFAULT NULL,
  `norsect` int(11) DEFAULT NULL,
  `chopping` tinyint(3) unsigned DEFAULT NULL,
  `obscal` tinyint(3) unsigned DEFAULT NULL,
  `obscen` tinyint(3) unsigned DEFAULT NULL,
  `obsfly` tinyint(3) unsigned DEFAULT NULL,
  `obsfocus` tinyint(3) unsigned DEFAULT NULL,
  `obsmap` tinyint(3) unsigned DEFAULT NULL,
  `obsmode` varchar(16) DEFAULT NULL,
  `coordcd` varchar(16) DEFAULT NULL,
  `coordcd2` int(11) DEFAULT NULL,
  `radate` double DEFAULT NULL,
  `decdate` double DEFAULT NULL,
  `az` double DEFAULT NULL,
  `el` double DEFAULT NULL,
  `restfrq1` double DEFAULT NULL,
  `restfrq2` double DEFAULT NULL,
  `velocity` double DEFAULT NULL,
  `vdef` varchar(16) DEFAULT NULL,
  `vref` varchar(16) DEFAULT NULL,
  `ut1c` double DEFAULT NULL,
  `lst` double DEFAULT NULL,
  `samprat` int(11) DEFAULT NULL,
  `nocycles` int(11) DEFAULT NULL,
  `cycllen` int(11) DEFAULT NULL,
  `noscans` int(11) DEFAULT NULL,
  `noscnpts` int(11) DEFAULT NULL,
  `nocycpts` int(11) DEFAULT NULL,
  `xcell0` float DEFAULT NULL,
  `ycell0` float DEFAULT NULL,
  `xref` double DEFAULT NULL,
  `yref` double DEFAULT NULL,
  `xsource` double DEFAULT NULL,
  `ysource` double DEFAULT NULL,
  `frame` varchar(16) DEFAULT NULL,
  `frame2` int(11) DEFAULT NULL,
  `xyangle` double DEFAULT NULL,
  `deltax` double DEFAULT NULL,
  `deltay` double DEFAULT NULL,
  `scanang` double DEFAULT NULL,
  `yposang` double DEFAULT NULL,
  `afocusv` float DEFAULT NULL,
  `afocush` float DEFAULT NULL,
  `afocusr` float DEFAULT NULL,
  `tcold` float DEFAULT NULL,
  `thot` float DEFAULT NULL,
  `noswvar` int(11) DEFAULT NULL,
  `nophase` int(11) DEFAULT NULL,
  `snstvty` int(11) DEFAULT NULL,
  `phase` int(11) DEFAULT NULL,
  `mapunit` varchar(16) DEFAULT NULL,
  `nomapdim` int(11) DEFAULT NULL,
  `nopts` int(11) DEFAULT NULL,
  `noxpts` int(11) DEFAULT NULL,
  `noypts` int(11) DEFAULT NULL,
  `reversal` tinyint(3) unsigned DEFAULT NULL,
  `directn` varchar(16) DEFAULT NULL,
  `xsign` tinyint(3) unsigned DEFAULT NULL,
  `ysign` tinyint(3) unsigned DEFAULT NULL,
  `spect` double DEFAULT NULL,
  `resp` float DEFAULT NULL,
  `stdspect` double DEFAULT NULL,
  `trms` double DEFAULT NULL,
  `radate_int` int(11) DEFAULT NULL,
  `decdate_int` int(11) DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  `polarity` varchar(6) DEFAULT NULL,
  `sbmode` varchar(6) DEFAULT NULL,
  UNIQUE KEY `SCAtupind` (`tuple_id`),
  UNIQUE KEY `SCAsca#ind` (`sca#`),
  KEY `SCAobjind` (`object`),
  KEY `SCAprojind` (`projid`),
  KEY `SCAsesind` (`ses#`),
  KEY `SCAsouind` (`sou#`),
  KEY `SCAtelind` (`tel#`),
  KEY `SCAutdmfind` (`ut_dmf`),
  KEY `SCAutind` (`ut`),
  KEY `SCAweaind` (`wea#`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `SCU` (
  `scu#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `scu_id` varchar(64) DEFAULT NULL,
  `sdffile` varchar(64) DEFAULT NULL,
  `proj_id` varchar(16) DEFAULT NULL,
  `run` smallint(6) DEFAULT NULL,
  `release_date` datetime DEFAULT NULL,
  `raj2000` double DEFAULT NULL,
  `decj2000` double DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `obj_type` varchar(16) DEFAULT NULL,
  `accept` varchar(16) DEFAULT NULL,
  `align_ax` varchar(8) DEFAULT NULL,
  `align_sh` double DEFAULT NULL,
  `alt_obs` double DEFAULT NULL,
  `amend` float DEFAULT NULL,
  `amstart` float DEFAULT NULL,
  `apend` float DEFAULT NULL,
  `apstart` float DEFAULT NULL,
  `atend` float DEFAULT NULL,
  `atstart` float DEFAULT NULL,
  `boloms` varchar(16) DEFAULT NULL,
  `calibrtr` char(1) DEFAULT NULL,
  `cal_frq` double DEFAULT NULL,
  `cent_crd` varchar(8) DEFAULT NULL,
  `chop_crd` varchar(8) DEFAULT NULL,
  `chop_frq` double DEFAULT NULL,
  `chop_fun` varchar(16) DEFAULT NULL,
  `chop_pa` float DEFAULT NULL,
  `chop_thr` float DEFAULT NULL,
  `data_dir` varchar(16) DEFAULT NULL,
  `drgroup` varchar(16) DEFAULT NULL,
  `drrecipe` varchar(24) DEFAULT NULL,
  `end_azd` float DEFAULT NULL,
  `end_el` float DEFAULT NULL,
  `end_eld` float DEFAULT NULL,
  `equinox` int(11) DEFAULT NULL,
  `exposed` float DEFAULT NULL,
  `exp_no` int(11) DEFAULT NULL,
  `exp_time` double DEFAULT NULL,
  `e_per_i` smallint(6) DEFAULT NULL,
  `filter` varchar(16) DEFAULT NULL,
  `focus_sh` double DEFAULT NULL,
  `gain` smallint(6) DEFAULT NULL,
  `hstend` varchar(20) DEFAULT NULL,
  `hststart` varchar(20) DEFAULT NULL,
  `humend` smallint(6) DEFAULT NULL,
  `humstart` smallint(6) DEFAULT NULL,
  `int_no` smallint(6) DEFAULT NULL,
  `jigl_cnt` smallint(6) DEFAULT NULL,
  `jigl_nam` varchar(40) DEFAULT NULL,
  `j_per_s` smallint(6) DEFAULT NULL,
  `j_repeat` smallint(6) DEFAULT NULL,
  `locl_crd` varchar(16) DEFAULT NULL,
  `long` varchar(16) DEFAULT NULL,
  `lat` varchar(16) DEFAULT NULL,
  `long2` varchar(16) DEFAULT NULL,
  `lat2` varchar(16) DEFAULT NULL,
  `map_hght` smallint(6) DEFAULT NULL,
  `map_pa` double DEFAULT NULL,
  `map_wdth` smallint(6) DEFAULT NULL,
  `map_x` float DEFAULT NULL,
  `map_y` float DEFAULT NULL,
  `max_el` double DEFAULT NULL,
  `meandec` double DEFAULT NULL,
  `meanra` double DEFAULT NULL,
  `meas_no` int(11) DEFAULT NULL,
  `min_el` double DEFAULT NULL,
  `mjd1` double DEFAULT NULL,
  `mjd2` double DEFAULT NULL,
  `mode` varchar(16) DEFAULT NULL,
  `n_int` smallint(6) DEFAULT NULL,
  `n_measur` smallint(6) DEFAULT NULL,
  `observer` varchar(16) DEFAULT NULL,
  `sam_crds` varchar(16) DEFAULT NULL,
  `sam_dx` double DEFAULT NULL,
  `sam_dy` double DEFAULT NULL,
  `sam_mode` varchar(8) DEFAULT NULL,
  `sam_pa` double DEFAULT NULL,
  `scan_rev` char(1) DEFAULT NULL,
  `start_el` double DEFAULT NULL,
  `state` varchar(40) DEFAULT NULL,
  `stend` varchar(16) DEFAULT NULL,
  `strt_azd` double DEFAULT NULL,
  `strt_eld` double DEFAULT NULL,
  `ststart` varchar(16) DEFAULT NULL,
  `swtch_md` varchar(8) DEFAULT NULL,
  `swtch_no` smallint(6) DEFAULT NULL,
  `s_per_e` smallint(6) DEFAULT NULL,
  `utdate` varchar(16) DEFAULT NULL,
  `utend` varchar(20) DEFAULT NULL,
  `utstart` varchar(20) DEFAULT NULL,
  `wvplate` smallint(6) DEFAULT NULL,
  `wpltname` varchar(64) DEFAULT NULL,
  `align_dx` float DEFAULT NULL,
  `align_dy` float DEFAULT NULL,
  `align_x` float DEFAULT NULL,
  `align_y` float DEFAULT NULL,
  `az_err` float DEFAULT NULL,
  `chopping` char(1) DEFAULT NULL,
  `el_err` float DEFAULT NULL,
  `focus_dz` float DEFAULT NULL,
  `focus_z` float DEFAULT NULL,
  `seeing` float DEFAULT NULL,
  `see_date` varchar(16) DEFAULT NULL,
  `tau_225` double DEFAULT NULL,
  `tau_date` varchar(16) DEFAULT NULL,
  `tau_rms` double DEFAULT NULL,
  `uaz` double DEFAULT NULL,
  `uel` double DEFAULT NULL,
  `ut_date` varchar(16) DEFAULT NULL,
  `chop_lg` int(11) DEFAULT NULL,
  `chop_pd` float DEFAULT NULL,
  `cntr_du3` float DEFAULT NULL,
  `cntr_du4` float DEFAULT NULL,
  `etatel_1` float DEFAULT NULL,
  `etatel_2` float DEFAULT NULL,
  `etatel_3` float DEFAULT NULL,
  `filt_350` smallint(6) DEFAULT NULL,
  `filt_450` smallint(6) DEFAULT NULL,
  `filt_750` smallint(6) DEFAULT NULL,
  `filt_850` smallint(6) DEFAULT NULL,
  `filt_1100` smallint(6) DEFAULT NULL,
  `filt_1350` smallint(6) DEFAULT NULL,
  `filt_2000` smallint(6) DEFAULT NULL,
  `filt_1` varchar(8) DEFAULT NULL,
  `filt_2` varchar(8) DEFAULT NULL,
  `filt_3` varchar(8) DEFAULT NULL,
  `flat` varchar(40) DEFAULT NULL,
  `meas_bol` varchar(16) DEFAULT NULL,
  `n_bols` smallint(6) DEFAULT NULL,
  `n_subs` smallint(6) DEFAULT NULL,
  `phot_bbf` varchar(40) DEFAULT NULL,
  `rebin` varchar(8) DEFAULT NULL,
  `ref_adc` double DEFAULT NULL,
  `ref_chan` double DEFAULT NULL,
  `sam_time` int(11) DEFAULT NULL,
  `simulate` char(1) DEFAULT NULL,
  `sub_1` varchar(8) DEFAULT NULL,
  `sub_2` varchar(8) DEFAULT NULL,
  `sub_3` varchar(8) DEFAULT NULL,
  `s_gd_bol` varchar(8) DEFAULT NULL,
  `s_guard` char(1) DEFAULT NULL,
  `tauz_1` float DEFAULT NULL,
  `tauz_2` float DEFAULT NULL,
  `tauz_3` float DEFAULT NULL,
  `t_amb` float DEFAULT NULL,
  `t_cold_1` float DEFAULT NULL,
  `t_cold_2` float DEFAULT NULL,
  `t_cold_3` float DEFAULT NULL,
  `t_hot` float DEFAULT NULL,
  `t_tel` float DEFAULT NULL,
  `wave_1` float DEFAULT NULL,
  `wave_2` float DEFAULT NULL,
  `wave_3` float DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `ra_int` int(11) DEFAULT NULL,
  `dec_int` int(11) DEFAULT NULL,
  `release_date_dmf` int(11) DEFAULT NULL,
  `msbid` varchar(40) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  `obsid` varchar(48) NOT NULL,
  UNIQUE KEY `SCUtupind` (`tuple_id`),
  UNIQUE KEY `SCUscu#ind` (`scu#`),
  UNIQUE KEY `SCUscuid` (`scu_id`),
  KEY `SCUdecjind` (`dec_int`),
  KEY `SCUmsbid` (`msbid`),
  KEY `SCUobjind` (`object`),
  KEY `SCUprojind` (`proj_id`),
  KEY `SCUrajind` (`ra_int`),
  KEY `SCUutdate` (`utdate`),
  KEY `SCUutdmfind` (`ut_dmf`),
  KEY `SCUutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `SES` (
  `ses#` int(11) DEFAULT NULL,
  `utstart` datetime DEFAULT NULL,
  `utstop` datetime DEFAULT NULL,
  `projid` varchar(16) DEFAULT NULL,
  `obsid` varchar(16) DEFAULT NULL,
  `observer` varchar(16) DEFAULT NULL,
  `operator` varchar(16) DEFAULT NULL,
  `telescop` varchar(16) DEFAULT NULL,
  `longitud` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `height` double DEFAULT NULL,
  `mounting` varchar(16) DEFAULT NULL,
  `utstart_dmf` int(11) DEFAULT NULL,
  `utstop_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `SEStupind` (`tuple_id`),
  UNIQUE KEY `SESses#ind` (`ses#`),
  KEY `SESprojind` (`projid`),
  KEY `SESut1dind` (`utstart_dmf`),
  KEY `SESut2dind` (`utstop_dmf`),
  KEY `SESutind` (`utstart`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `SOU` (
  `sou#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `cenmove` tinyint(3) unsigned DEFAULT NULL,
  `epoch` double DEFAULT NULL,
  `epochtyp` varchar(16) DEFAULT NULL,
  `epocra` double DEFAULT NULL,
  `epocdec` double DEFAULT NULL,
  `raj2000` double DEFAULT NULL,
  `decj2000` double DEFAULT NULL,
  `gallong` double DEFAULT NULL,
  `gallat` double DEFAULT NULL,
  `epocra_int` int(11) DEFAULT NULL,
  `epocdec_int` int(11) DEFAULT NULL,
  `raj2000_int` int(11) DEFAULT NULL,
  `decj2000_int` int(11) DEFAULT NULL,
  `gallong_int` int(11) DEFAULT NULL,
  `gallat_int` int(11) DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `SOUtupind` (`tuple_id`),
  UNIQUE KEY `SOUsou#ind` (`sou#`),
  KEY `SOUdecind` (`epocdec`),
  KEY `SOUidecind` (`epocdec_int`),
  KEY `SOUiraind` (`epocra_int`),
  KEY `SOUobjind` (`object`),
  KEY `SOUraind` (`epocra`),
  KEY `SOUutdmfind` (`ut_dmf`),
  KEY `SOUutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `SPH` (
  `sph#` int(11) DEFAULT NULL,
  `sca#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `projid` varchar(16) DEFAULT NULL,
  `scan` int(11) DEFAULT NULL,
  `band` int(11) DEFAULT NULL,
  `backend` varchar(16) DEFAULT NULL,
  `filter` varchar(16) DEFAULT NULL,
  `aperture` varchar(16) DEFAULT NULL,
  `spect` double DEFAULT NULL,
  `resp` float DEFAULT NULL,
  `stdspect` double DEFAULT NULL,
  `trms` double DEFAULT NULL,
  `cyclrev` int(11) DEFAULT NULL,
  `sntvtyrg` varchar(16) DEFAULT NULL,
  `timecnst` varchar(16) DEFAULT NULL,
  `freqres` float DEFAULT NULL,
  `obsfreq` double DEFAULT NULL,
  `restfreq` double DEFAULT NULL,
  `befenulo` double DEFAULT NULL,
  `bw` float DEFAULT NULL,
  `trx` float DEFAULT NULL,
  `stsys` float DEFAULT NULL,
  `tsky` float DEFAULT NULL,
  `ttel` float DEFAULT NULL,
  `gains` float DEFAULT NULL,
  `tcal` float DEFAULT NULL,
  `tauh2o` float DEFAULT NULL,
  `eta_sky` float DEFAULT NULL,
  `alpha` float DEFAULT NULL,
  `g_s` float DEFAULT NULL,
  `eta_tel` float DEFAULT NULL,
  `t_sky_im` float DEFAULT NULL,
  `eta_sky_im` float DEFAULT NULL,
  `t_sys_im` float DEFAULT NULL,
  `ta_sky` float DEFAULT NULL,
  `cm` int(11) DEFAULT NULL,
  `bm` int(11) DEFAULT NULL,
  `overlap` float DEFAULT NULL,
  `bescon` int(11) DEFAULT NULL,
  `nobesdch` int(11) DEFAULT NULL,
  `besspec` int(11) DEFAULT NULL,
  `betotif` double DEFAULT NULL,
  `befesb` int(11) DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  `mixer_id` int(11) DEFAULT NULL,
  UNIQUE KEY `SPHtupind` (`tuple_id`),
  UNIQUE KEY `SPHsph#ind` (`sph#`),
  KEY `SPHprojind` (`projid`),
  KEY `SPHsca#ind` (`sca#`),
  KEY `SPHutdmfind` (`ut_dmf`),
  KEY `SPHutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `STA` (
  `sta#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `sca#` int(11) DEFAULT NULL,
  `tdv` float DEFAULT NULL,
  `sb` char(3) DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `STAtupind` (`tuple_id`),
  UNIQUE KEY `STAsta#ind` (`sta#`),
  KEY `STAscaind` (`sca#`),
  KEY `STAutdind` (`ut_dmf`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `STSOU` (
  `stsou#` int(11) DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `STSOUtupind` (`tuple_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `SUB` (
  `sub#` int(11) DEFAULT NULL,
  `sca#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `projid` varchar(16) DEFAULT NULL,
  `scan` double DEFAULT NULL,
  `subscan` smallint(6) DEFAULT NULL,
  `xcell0` float DEFAULT NULL,
  `ycell0` float DEFAULT NULL,
  `lst` double DEFAULT NULL,
  `airmass` double DEFAULT NULL,
  `samprat` int(11) DEFAULT NULL,
  `nocycles` int(11) DEFAULT NULL,
  `ncycle` int(11) DEFAULT NULL,
  `cycllen` int(11) DEFAULT NULL,
  `noscans` int(11) DEFAULT NULL,
  `nscan` int(11) DEFAULT NULL,
  `noscnpts` int(11) DEFAULT NULL,
  `nocycpts` int(11) DEFAULT NULL,
  `ncycpts` int(11) DEFAULT NULL,
  `intgr` int(11) DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `SUBtupind` (`tuple_id`),
  UNIQUE KEY `SUBsub#ind` (`sub#`),
  KEY `SUBprojind` (`projid`),
  KEY `SUBsca#ind` (`sca#`),
  KEY `SUButdmfind` (`ut_dmf`),
  KEY `SUButind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `TAU` (
  `tau#` int(11) DEFAULT NULL,
  `cso_ut` datetime DEFAULT NULL,
  `hst` float DEFAULT NULL,
  `tau` float DEFAULT NULL,
  `tau_rms` float DEFAULT NULL,
  `cso_ut_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `TAUtau#ind` (`tau#`),
  KEY `TAUcsodmfind` (`cso_ut_dmf`),
  KEY `TAUcsoutind` (`cso_ut`),
  KEY `TAUtupind` (`tuple_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `TEL` (
  `tel#` int(11) DEFAULT NULL,
  `fe#` int(11) DEFAULT NULL,
  `eff#` int(11) DEFAULT NULL,
  `be#` int(11) DEFAULT NULL,
  `smu#` int(11) DEFAULT NULL,
  `poi#` int(11) DEFAULT NULL,
  `foc#` int(11) DEFAULT NULL,
  `utstart` datetime DEFAULT NULL,
  `utstop` datetime DEFAULT NULL,
  `projid` varchar(16) DEFAULT NULL,
  `scan` int(11) DEFAULT NULL,
  `frontend` varchar(16) DEFAULT NULL,
  `frontype` varchar(16) DEFAULT NULL,
  `nofchan` int(11) DEFAULT NULL,
  `backend` varchar(16) DEFAULT NULL,
  `backtype` varchar(16) DEFAULT NULL,
  `noifpbes` int(11) DEFAULT NULL,
  `nobchan` int(11) DEFAULT NULL,
  `config` int(11) DEFAULT NULL,
  `outputt` varchar(16) DEFAULT NULL,
  `calsrc` varchar(16) DEFAULT NULL,
  `shftfrac` float DEFAULT NULL,
  `badchv` double DEFAULT NULL,
  `norchan` int(11) DEFAULT NULL,
  `norsect` int(11) DEFAULT NULL,
  `dataunit` varchar(16) DEFAULT NULL,
  `swmode` varchar(16) DEFAULT NULL,
  `caltask` varchar(16) DEFAULT NULL,
  `caltype` varchar(16) DEFAULT NULL,
  `redmode` varchar(16) DEFAULT NULL,
  `waveform` varchar(16) DEFAULT NULL,
  `chopfreq` float DEFAULT NULL,
  `chopcoor` varchar(16) DEFAULT NULL,
  `chopthrw` float DEFAULT NULL,
  `chopdirn` float DEFAULT NULL,
  `ewtilt` float DEFAULT NULL,
  `nstilt` float DEFAULT NULL,
  `ew_scale` float DEFAULT NULL,
  `ns_scale` float DEFAULT NULL,
  `ew_encode` int(11) DEFAULT NULL,
  `ns_encode` int(11) DEFAULT NULL,
  `xpoint` double DEFAULT NULL,
  `ypoint` double DEFAULT NULL,
  `uxpnt` double DEFAULT NULL,
  `uypnt` double DEFAULT NULL,
  `focusv` float DEFAULT NULL,
  `focusl` float DEFAULT NULL,
  `focusr` float DEFAULT NULL,
  `utstart_dmf` int(11) DEFAULT NULL,
  `utstop_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `TELtupind` (`tuple_id`),
  UNIQUE KEY `TELtel#ind` (`tel#`),
  KEY `TELprojind` (`projid`),
  KEY `TELut1dind` (`utstart_dmf`),
  KEY `TELut2dind` (`utstop_dmf`),
  KEY `TELutind` (`utstart`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `THI` (
  `thi#` smallint(6) DEFAULT NULL,
  `az` float DEFAULT NULL,
  `f1` float DEFAULT NULL,
  `f2` float DEFAULT NULL,
  `f3` float DEFAULT NULL,
  UNIQUE KEY `THIthiind` (`thi#`),
  KEY `THIazind` (`az`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `WEA` (
  `wea#` int(11) DEFAULT NULL,
  `utstart` datetime DEFAULT NULL,
  `utstop` datetime DEFAULT NULL,
  `projid` varchar(16) DEFAULT NULL,
  `scan` int(11) DEFAULT NULL,
  `ws#` int(11) DEFAULT NULL,
  `tau#` int(11) DEFAULT NULL,
  `pha#` int(11) DEFAULT NULL,
  `tamb` float DEFAULT NULL,
  `pressure` float DEFAULT NULL,
  `humidity` float DEFAULT NULL,
  `tau` float DEFAULT NULL,
  `tau_rms` float DEFAULT NULL,
  `tau_date` datetime DEFAULT NULL,
  `pha` float DEFAULT NULL,
  `pha_date` datetime DEFAULT NULL,
  `utstart_dmf` int(11) DEFAULT NULL,
  `utstop_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `WEAtupind` (`tuple_id`),
  UNIQUE KEY `WEAwea#ind` (`wea#`),
  KEY `WEAprojind` (`projid`),
  KEY `WEAut1dind` (`utstart_dmf`),
  KEY `WEAut2dind` (`utstop_dmf`),
  KEY `WEAutind` (`utstart`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `WS` (
  `ws#` int(11) DEFAULT NULL,
  `ut` datetime DEFAULT NULL,
  `period` varchar(16) DEFAULT NULL,
  `name` varchar(16) DEFAULT NULL,
  `avgval` float DEFAULT NULL,
  `minval` float DEFAULT NULL,
  `maxval` float DEFAULT NULL,
  `npts` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `WSws#ind` (`ws#`),
  KEY `WSutind` (`ut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `scan` (
  `dir_id` varchar(107) DEFAULT NULL,
  `scan_id` varchar(120) DEFAULT NULL,
  `projid` varchar(16) DEFAULT NULL,
  `scan` int(11) DEFAULT NULL,
  `sca_idx` int(11) DEFAULT NULL,
  `release_date` datetime DEFAULT NULL,
  `obsmode` varchar(16) DEFAULT NULL,
  `lst` double DEFAULT NULL,
  `utdate` datetime DEFAULT NULL,
  `uthour` float DEFAULT NULL,
  `ra` double DEFAULT NULL,
  `dec` double DEFAULT NULL,
  `lii` double DEFAULT NULL,
  `bii` double DEFAULT NULL,
  `azimuth` double DEFAULT NULL,
  `elevation` double DEFAULT NULL,
  `epoch` double DEFAULT NULL,
  `ra_epoch` double DEFAULT NULL,
  `dec_epoch` double DEFAULT NULL,
  `ncycle` int(11) DEFAULT NULL,
  `cycllen` int(11) DEFAULT NULL,
  `coordcd` varchar(16) DEFAULT NULL,
  `deltax` double DEFAULT NULL,
  `deltay` double DEFAULT NULL,
  `yposang` double DEFAULT NULL,
  `xsource` double DEFAULT NULL,
  `ysource` double DEFAULT NULL,
  `xmap` int(11) DEFAULT NULL,
  `ymap` int(11) DEFAULT NULL,
  `object` varchar(16) DEFAULT NULL,
  `nscan` int(11) DEFAULT NULL,
  `frontend` varchar(16) DEFAULT NULL,
  `frontype` varchar(16) DEFAULT NULL,
  `backend` varchar(16) DEFAULT NULL,
  `backtype` varchar(16) DEFAULT NULL,
  `velocity` double DEFAULT NULL,
  `restfreq` double DEFAULT NULL,
  `freqres` float DEFAULT NULL,
  `veldef` varchar(16) DEFAULT NULL,
  `velref` varchar(16) DEFAULT NULL,
  `nobchan` int(11) DEFAULT NULL,
  `norsect` int(11) DEFAULT NULL,
  `swmode` varchar(27) DEFAULT NULL,
  `chopfreq` float DEFAULT NULL,
  `filter` varchar(16) DEFAULT NULL,
  `aperture` varchar(16) DEFAULT NULL,
  `photometry` double DEFAULT NULL,
  `phot_error` double DEFAULT NULL,
  `tsys` float DEFAULT NULL,
  `tau` float DEFAULT NULL,
  `seeing` float DEFAULT NULL,
  `tamb` float DEFAULT NULL,
  `humidity` float DEFAULT NULL,
  `epocra_int` int(11) DEFAULT NULL,
  `epocdec_int` int(11) DEFAULT NULL,
  `ra_int` int(11) DEFAULT NULL,
  `dec_int` int(11) DEFAULT NULL,
  `lii_int` int(11) DEFAULT NULL,
  `bii_int` int(11) DEFAULT NULL,
  `ut_dmf` int(11) DEFAULT NULL,
  `release_date_dmf` int(11) DEFAULT NULL,
  `tuple_id` int(11) NOT NULL,
  UNIQUE KEY `scanscaid` (`sca_idx`),
  KEY `scandutind` (`ut_dmf`),
  KEY `scaneradec` (`epocra_int`,`epocdec_int`),
  KEY `scanobj` (`object`),
  KEY `scanprojind` (`projid`),
  KEY `scanradec` (`ra_int`,`dec_int`),
  KEY `scanrf` (`restfreq`),
  KEY `scanutind` (`utdate`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
